### ISSUE TITLE
p.46

### ISSUE THREAD

**Issue by Ninagawa123** [AI-Robot-Book/errata#2]
3.パッケージの作成でつくるパッケージとノードはhello_node helloであっているでしょうか。
もしくはhappy_node happyでしょうか？

**Comment by demuko** [comment]
ご指摘ありがとうございます．p.46はあっていますが，プログラムリスト2.1，プログラムリスト2.2のコードにあるhappyはhelloの間違いです．p.47の7, 8行目のhappyもhelloの間違いです．happy_nodeはp.50からです．お詫びして訂正します．
